// Originally generated by scripts/extract-art.py, since removed — this
// file is now hand-maintained. Edit with care: DESIGN must still match
// the actual backdrop image's pixel dimensions, and REGIONS must still
// be concept pixels within it, or badges land in the wrong spot.
//
// The backdrop and everything positioned against it. Hotspot
// coordinates are percentages of the backdrop, derived from anchors
// given in concept pixels, so the two cannot drift apart.
//
// The whole screen is this many pixels, scaled uniformly to the
// window, so these are also plain CSS pixels inside the design box.

export const DESIGN = { width: 1376, height: 768 };

export const REGIONS = {
  union: { left: 365, top: 200, align: "center" },
  politicians: { left: 877, top: 200, align: "center" },
  hospital: { left: 845, top: 320, align: "center" },
  police: { left: 1040, top: 400, align: "right" },
  mines: { left: 400, top: 320, align: "center" },
  smelter: { left: 330, top: 430, align: "left" },
};
