// Generated by scripts/extract-art.py — do not edit by hand.
//
// The backdrop and everything positioned against it. Hotspot
// coordinates are percentages of the backdrop, derived from anchors
// given in concept pixels, so the two cannot drift apart.
//
// The backdrop is drawn `cover`, so a percentage of the image is not
// a percentage of the window: Backdrop.jsx does that conversion.

export const BACKDROP_ASPECT = 1376 / 768;

export const REGIONS = {
  union: { left: "26.5%", top: "26.0%", align: "center" },
  politicians: { left: "63.7%", top: "26.0%", align: "center" },
  hospital: { left: "61.4%", top: "41.7%", align: "center" },
  police: { left: "75.6%", top: "52.1%", align: "right" },
  mines: { left: "29.1%", top: "41.7%", align: "center" },
  smelter: { left: "24.0%", top: "56.0%", align: "left" },
};
