// Originally generated by scripts/extract-art.py, since removed — this
// file is now hand-maintained. Edit with care: DESIGN must still match
// the actual backdrop image's pixel dimensions, and REGIONS must still
// be concept pixels within it, or badges land in the wrong spot.
//
// The backdrop and everything positioned against it. Hotspot
// coordinates are percentages of the backdrop, derived from anchors
// given in concept pixels, so the two cannot drift apart.
//
// The whole screen is this many pixels, scaled uniformly to the
// window, so these are also plain CSS pixels inside the design box.

// Root-relative "/art/..." paths break once the app is served from a
// subpath (e.g. itch.io's HTML embed), because Vite's `base` only
// rewrites assets it processes itself, not raw strings in JS/CSS.
// BASE_URL is already resolved against `base` at build time, but it's
// still relative ("./") — fine for a plain <img src>, which resolves
// against the document, but not for a url() stashed in a CSS custom
// property and read back via var() from an externally-linked
// stylesheet: the spec resolves that relative to the *stylesheet's*
// location (assets/), not the page's, so it 404s one directory too
// deep. Resolving to an absolute URL up front sidesteps the ambiguity
// everywhere ART_BASE is used.
export const ART_BASE = new URL(
  `${import.meta.env.BASE_URL}art/`,
  document.baseURI
).href;

export const DESIGN = { width: 1376, height: 768 };

export const REGIONS = {
  union: { left: 365, top: 200, align: "center" },
  politicians: { left: 877, top: 200, align: "center" },
  hospital: { left: 845, top: 320, align: "center" },
  police: { left: 1040, top: 400, align: "right" },
  mines: { left: 400, top: 320, align: "center" },
  smelter: { left: 330, top: 430, align: "left" },
};
